export const GET_CHARACTERS = 'GET_ALL_CHARACTERS';
export const ADD_NEW_CHARACTERS = 'ADD_NEW_CHARACTERS';
export const SET_LIST_CHARACTERS = 'SET_LIST_CHARACTERS';
export const SET_CURRENT_PAGE_OF_CHARACTERS = 'SET_CURRENT_PAGE_OF_CHARACTERS';
export const SET_SELECTED_CHARACTERS = 'SET_SELECTED_CHARACTERS';
export const SET_DEFAULT_LIST_CHARACTERS = 'SET_DEFAULT_LIST_CHARACTERS';
export const GET_API_CHARACTERS_BY_SEARCH_PARAMS = 'GET_API_CHARACTERS_BY_SEARCH_PARAMS';
export const UPDATE_API_CHARACTERS_BY_NAME = 'UPDATE_API_CHARACTERS_BY_NAME';
export const UPDATING_CHARACTERS_BY_PARAMS_START = 'UPDATING_CHARACTERS_BY_PARAMS_START';
export const UPDATING_CHARACTERS_BY_PARAMS_SUCCESS = 'UPDATING_CHARACTERS_BY_PARAMS_SUCCESS';
export const LOADING_OF_CHARACTERS_START = 'LOADING_OF_CHARACTERS_START';
export const LOADING_OF_CHARACTERS_SUCCESS = 'LOADING_OF_CHARACTERS_SUCCESS';

// actionTypes characters
