export const GET_LOCATIONS = 'GET_ALL_LOCATIONS';
export const ADD_NEW_LOCATIONS = 'ADD_NEW_LOCATIONS';
export const SET_LIST_LOCATIONS = 'SET_LIST_LOCATIONS';
export const SET_CURRENT_PAGE_OF_LOCATIONS = 'SET_CURRENT_PAGE_OF_LOCATIONS';
export const SET_SELECTED_LOCATIONS = 'SET_SELECTED_LOCATIONS';
export const SET_DEFAULT_LIST_LOCATIONS = 'SET_DEFAULT_LIST_LOCATIONS';
export const GET_API_LOCATIONS_BY_SEARCH_PARAMS = 'GET_API_LOCATIONS_BY_SEARCH_PARAMS';
export const UPDATE_API_LOCATIONS_BY_NAME = 'UPDATE_API_LOCATIONS_BY_NAME';
export const UPDATING_LOCATIONS_BY_PARAMS_START = 'UPDATING_LOCATIONS_BY_PARAMS_START';
export const UPDATING_LOCATIONS_BY_PARAMS_SUCCESS = 'UPDATING_LOCATIONS_BY_PARAMS_SUCCESS';
export const LOADING_OF_LOCATIONS_START = 'LOADING_OF_LOCATIONS_START';
export const LOADING_OF_LOCATIONS_SUCCESS = 'LOADING_OF_LOCATIONS_SUCCESS';

// actionTypes locations

