export const GET_EPISODES = 'GET_ALL_EPISODES';
export const ADD_NEW_EPISODES = 'ADD_NEW_EPISODES';
export const SET_LIST_EPISODES = 'SET_LIST_EPISODES';
export const SET_CURRENT_PAGE_OF_EPISODES = 'SET_CURRENT_PAGE_OF_EPISODES';
export const SET_SELECTED_EPISODES = 'SET_SELECTED_EPISODES';
export const SET_DEFAULT_LIST_EPISODES = 'SET_DEFAULT_LIST_EPISODES';
export const GET_API_EPISODES_BY_SEARCH_PARAMS = 'GET_API_EPISODES_BY_SEARCH_PARAMS';
export const UPDATE_API_EPISODES_BY_NAME = 'UPDATE_API_EPISODES_BY_NAME';
export const UPDATING_EPISODES_BY_PARAMS_START = 'UPDATING_EPISODES_BY_PARAMS_START';
export const UPDATING_EPISODES_BY_PARAMS_SUCCESS = 'UPDATING_EPISODES_BY_PARAMS_SUCCESS';
export const LOADING_OF_EPISODES_START = 'LOADING_OF_EPISODES_START';
export const LOADING_OF_EPISODES_SUCCESS = 'LOADING_OF_EPISODES_SUCCESS';

// actionTypes episodes
